### ISSUE TITLE
It seems like the live web demo isn't working?

### ISSUE THREAD

**Issue by dhall1995** [AstraZeneca/KAZU#3]
Hi there,

Very cool repo + documentation thankyou for sharing. I wanted to watch the live demo as i'm currently facing a thorny NER/RE problem in the plant sciences space. However the live web demo link appears to be broken?

all the best,

Dominic

**Comment by wonjininfo** [comment]
Hi Dominic,

My apologies for the inconvenience. The school servers are currently down for maintenance due to cooling issues in our server room. I am working on resolving the issue and also exploring alternative external servers to host our systems in case of similar incidents in the future. I will keep you updated on the progress through this issue!

Best,
Wonjin

**Comment by wonjininfo** [comment]
Hi Dominic,

I apologise for the extended delays. The process of fixing the air conditioners in the server space of my previous department took longer than expected. However, I'm pleased to inform you that the server is now up and running.

Please let me know if there are any other issues or concerns.

Best,
Wonjin

**Comment by dhall1995** [comment]
Great thanks!

**Comment by EFord36** [comment]
Hi - it looks like this issue can be closed now. Feel free to reopen or open a new issue if you are facing other ones!
